### ISSUE TITLE
plugin seems broken

### ISSUE THREAD

**Issue by exoess** [timgott/wayfire-shadows#20]
when i try to build i get an incredibly long error that i don't understand in the least, i can send the error message but as i said it's very long

**Comment by timgott** [comment]
Hi, you have to give more information to make this a useful report, like in which step the error occurred, what distro you are using.

You also absolutely have to send the log or the error message, otherwise nothing can be done. Most likely the error is printed in red but you should attach the entire log if you don't understand it. If it really is too long to put into a code block then attach it as a file.
